### ISSUE TITLE
Is this still maintained ?

### ISSUE THREAD

**Issue by CodingMinds** [ngs/go-amazon-product-advertising-api#11]
Is this project still maintained or is there anyone how want's to adopt this project (or already has) ?

**Comment by unicod3** [comment]
any update on this? @ngs

**Comment by ngs** [comment]
Sorry for late reply, I missed this issue.

This library is still maintained and working in my production code.

Proposals and patches for new features are welcomed, thanks.

**Comment by matrixik** [comment]
@ngs There are 5 open pull requests.
